name: Build Windows App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Repo'yu Klonla
      uses: actions/checkout@v3

    - name: Java 25 Ortamını Kur
      uses: actions/setup-java@v3
      with:
        java-version: '25'
        distribution: 'oracle' 

    - name: Maven ve jlink ile Windows Paketi Üret
      run: mvn clean javafx:jlink

    - name: Derlenen Paketi Artifact Olarak Yükle
      uses: actions/upload-artifact@v3
      with:
        name: LoveCounter-Windows-Paketi
        path: target/image/
