name: Build Windows App

on:
  push:
    branches: [ "main" ] # Eğer varsayılan dalın "master" ise burayı "master" olarak değiştir.
  workflow_dispatch: # GitHub üzerinden butona basarak manuel çalıştırmanı sağlar.

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Repo'yu Klonla
      uses: actions/checkout@v4

    - name: Java 25 Ortamını Kur
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin' # Kararlı ve açık kaynaklı dağıtım
        cache: 'maven' # Süreçleri hızlandırmak için kütüphaneleri önbelleğe alır

    - name: Maven ve jlink ile Windows Paketi Üret
      run: mvn clean javafx:jlink

    - name: Derlenen Paketi Artifact Olarak Yükle
      uses: actions/upload-artifact@v4
      with:
        name: LoveCounter-Windows-Paketi
        path: target/image/ # jlink komutunun Windows çıktılarını attığı varsayılan klasör
